spring:
  profiles:
    active: dev2
  datasource:
    url: jdbc:mysql://localhost:3306/my_chat?user=root
    username: root
    password: zyt646997
  mail:
    host: smtp.163.com
    username: zhou19970829yuntao@163.com
    password: TEEZQGEKBERVTDXV
    protocol: smtps
    properties:
      "mail.smtp.auth": true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.robertZhou.chat.entity

#配置log4j2的配置文件地址
logging:
  config: classpath:config/Log4j2.xml

server:
  port: 8999
  ws:
    port: 9999


